export const Navlinks = [
  { label: "Home", link: "#home" },
  { label: "Shop", link: "#shop" },
  { label: "About", link: "#about" },
  { label: "Contact", link: "#contact" },
];

export const Catagories = [
  { label: "New Trends"},
  { label: "Nike" },
  { label: "Adidas" },
  { label: "Champion" },
  { label: "Random" },
  { label: "Shoe" },
  { label: "T-Shirt" },
  { label: "Cultural" },
];

export const Items = [
  {
    label: "Adidas Quality",
    image: "/adidas-shoe1.jpeg",
    salary: "99",
    brand: "adidas",
    catagory: "shoe",
    cultural: "no",
  },
  {
    label: "Adidas Q3",
    image: "/adidas-shoe2.jpeg",
    salary: "92",
    brand: "adidas",
    catagory: "shoe",
    cultural: "no",
  },{
    label: "Adidas A7",
    image: "/adidas-shoe3.jpeg",
    salary: "71",
    brand: "adidas",
    catagory: "shoe",
    cultural: "no",
  },{
    label: "Adidas Quality",
    image: "/adidas-t1.jpeg",
    salary: "17",
    brand: "adidas",
    catagory: "tshirt",
    cultural: "no",
  },{
    label: "Adidas T2",
    image: "/adidas-t2.jpeg",
    salary: "21",
    brand: "adidas",
    catagory: "tshirt",
    cultural: "no",
  },{
    label: "Champion Q6",
    image: "/cham-t1.jpeg",
    salary: "19",
    brand: "champion",
    catagory: "tshirt",
    cultural: "no",
  },{
    label: "Champion A1",
    image: "/cham-t2.jpeg",
    salary: "19",
    brand: "champion",
    catagory: "tshirt",
    cultural: "no",
  },{
    label: "Nike Az",
    image: "/nike-shoe.jpeg",
    salary: "67",
    brand: "nike",
    catagory: "shoe",
    cultural: "no",
  },{
    label: "Nike F6",
    image: "/nike-shoe2.jpeg",
    salary: "99",
    brand: "nike",
    catagory: "shoe",
    cultural: "no",
  },{
    label: "Nike Z3",
    image: "/nike-shoe3.jpeg",
    salary: "92",
    brand: "nike",
    catagory: "shoe",
    cultural: "no",
  },{
    label: "Nike T4",
    image: "/t2.jpeg",
    salary: "19",
    brand: "nike",
    catagory: "tshirt",
    cultural: "no",
  },{
    label: "Nike P9",
    image: "/nike-3.jpeg",
    salary: "17",
    brand: "nike",
    catagory: "tshirt",
    cultural: "no",
  },{
    label: "TShirt S45",
    image: "/Rand-t1.jpeg",
    salary: "17",
    brand: "random",
    catagory: "tshirt",
    cultural: "no",
  },
  {
    label: "TShirt D5",
    image: "/rand-t2.jpeg",
    salary: "17",
    brand: "random",
    catagory: "tshirt",
    cultural: "no",
  },
  {
    label: "Shoe D6",
    image: "/rand-shoe-2.jpg",
    salary: "49",
    brand: "random",
    catagory: "shoe",
    cultural: "no",
  },{
    label: "Shoe Y67",
    image: "/rand-shoe.jpeg",
    salary: "56",
    brand: "random",
    catagory: "shoe",
    cultural: "no",
  },
];
